Добвление UsersController с возможностью создания User используя createUser метода UsersServiсe
RezuanD/first_project pull request #3
Opened 2024-02-29 09:54 UTC by RezuanD

2024-02-29 14:30 UTC, sefaplus requested changes

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/dto/user.dto.ts
> +  @ApiProperty()
Для загрузки файлов через Swagger =>
@ApiProperty({ type: 'string', format: 'binary' })

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/helpers/users.helpers.ts
> +    userId: string,
id

и пробрасываем findOneBy({ id })

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/user.contoller.ts
> +    return await this.usersService.deleteUser(userId);
недопустимая конструкция return await

т.к. функция в любом случае async возвращает promise

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/helpers/users.helpers.ts
> +    }
Code style 
разделяем логические блоки строками

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/users.service.ts
> +    ) {
Ужас какой то :D

Вынест в переменную 
```ts
const foundUser = await this.userRepository.findOne({
  where: [
      { username },
      { email }
  ]
})
```

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/users.service.ts
> +  async create(user: CreateUserDto): Promise<CreatedUser> {
```ts
async create({ username, email }: CreateUserDto): Promise<CreatedUser> {
```

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/users.service.ts
> +    const { password, avatar, ...restUser } = createdUser;
не забываем строки между логическими блоками, для читаемости)

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/users.service.ts
> +  async deleteUser(userId: string): Promise<boolean> {
соблюдаем нейминг
Если этот метод deleteUser

то и getUserById должен быть findUser или тип того

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/user.contoller.ts
> +  @ApiResponse({ status: 204, description: 'User successfully deleted' })
Юзаем специальные декораторы
@ApiOkResponse()

https://docs.nestjs.com/openapi/operations#responses

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/user.contoller.ts
> +    return await this.usersService.create(createUserDto);
return await

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/users.service.ts
> +  saltOrRounds: number = 10;
Вынести в ENV
Недопусьимо хранить в сервисе

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/helpers/users.helpers.ts
> +export class UsersHelper {
Это будущая коллекция Helper-ов

Нейминг будет ближе к UserHelpers

2024-02-29 14:30 UTC, sefaplus commented on backend/src/users/helpers/users.helpers.ts
> +import { User } from '../user.entity';
настроить в tsconfig path alias

import { User } from '@/users/user.entity';

2024-03-01 07:32 UTC, RezuanD commented on backend/src/users/user.contoller.ts
> +  @ApiResponse({ status: 204, description: 'User successfully deleted' })
Я просто не нашел подходящий респонс, подумал ок не самый лучгий варинат для этого

2024-03-01 07:46 UTC, RezuanD commented on backend/src/users/users.service.ts
> +  async deleteUser(userId: string): Promise<boolean> {
Просто типо штука с тем чтобы писать название функции более понятной и описывать ее функционал без документации. Ну это опять же из питона скорее

2024-03-01 07:46 UTC, RezuanD commented on backend/src/users/users.service.ts
> +  async create(user: CreateUserDto): Promise<CreatedUser> {
Тут распаковка я так понял происходит?

2024-03-01 09:24 UTC, sefaplus requested changes

2024-03-01 09:24 UTC, sefaplus commented on backend/src/app.module.ts
> +    UsersModule,
Проглядел в прошлый раз.
Все сущности Module, Controller, Service называют единственный числом

UserModule, UserController, UserService
user.module.ts, user.controller.ts, user.service.ts

А коллекция методов хелпера правильно, UserHelpers т.к. это хелпер(ы) (<< важно что их много ) пользователя)

2024-03-01 09:24 UTC, sefaplus commented on backend/src/users/users.service.ts
> +  async create(user: CreateUserDto): Promise<CreatedUser> {
Да, в JS это десктруктуризация)

2024-03-01 09:24 UTC, sefaplus commented on backend/src/users/users.service.ts
> +    for (const fieldName of Object.keys(userUpdateDto)) {
можно по идее заменить на spead оператор в .save()
в духе, только чекни чтобы пароль не затерся
```ts
return foundUser.save({ ...foundUser, ...userUpdateDto }); 
```

2024-03-01 09:24 UTC, sefaplus commented on backend/src/users/users.service.ts
> +    for (const fieldName of Object.keys(userUpdateDto)) {
возможно что то в духе

```ts
return foundUser.save({ 
  ...foundUser, 
  ...userUpdateDto,
  password: password && await this.usersHelper.hashPassword(
        userUpdateDto.password,
        this.saltOrRounds,
      );
  }); 
```

2024-03-03 20:14 UTC, merged